// Code generated by Kitex v0.7.0. DO NOT EDIT.

package followservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	follow "pro2/follow/kitex_gen/follow"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Follow(ctx context.Context, Req *follow.DouyinRelationActionRequest, callOptions ...callopt.Option) (r *follow.DouyinRelationActionResponse, err error)
	FollowList(ctx context.Context, Req *follow.DouyinRelationFollowListRequest, callOptions ...callopt.Option) (r *follow.DouyinRelationFollowListResponse, err error)
	FollowerList(ctx context.Context, Req *follow.DouyinRelationFollowerListRequest, callOptions ...callopt.Option) (r *follow.DouyinRelationFollowerListResponse, err error)
	FriendList(ctx context.Context, Req *follow.DouyinRelationFriendListRequest, callOptions ...callopt.Option) (r *follow.DouyinRelationFriendListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFollowServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFollowServiceClient struct {
	*kClient
}

func (p *kFollowServiceClient) Follow(ctx context.Context, Req *follow.DouyinRelationActionRequest, callOptions ...callopt.Option) (r *follow.DouyinRelationActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Follow(ctx, Req)
}

func (p *kFollowServiceClient) FollowList(ctx context.Context, Req *follow.DouyinRelationFollowListRequest, callOptions ...callopt.Option) (r *follow.DouyinRelationFollowListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowList(ctx, Req)
}

func (p *kFollowServiceClient) FollowerList(ctx context.Context, Req *follow.DouyinRelationFollowerListRequest, callOptions ...callopt.Option) (r *follow.DouyinRelationFollowerListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowerList(ctx, Req)
}

func (p *kFollowServiceClient) FriendList(ctx context.Context, Req *follow.DouyinRelationFriendListRequest, callOptions ...callopt.Option) (r *follow.DouyinRelationFriendListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FriendList(ctx, Req)
}
