// Code generated by Kitex v0.7.0. DO NOT EDIT.

package likeservice

import (
	"context"
	likes "pro2/like/kitex_gen/likes"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	LikeAction(ctx context.Context, Req *likes.DouyinFavoriteActionRequest, callOptions ...callopt.Option) (r *likes.DouyinFavoriteActionResponse, err error)
	LikeList(ctx context.Context, Req *likes.DouyinFavoriteListRequest, callOptions ...callopt.Option) (r *likes.DouyinFavoriteListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kLikeServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kLikeServiceClient struct {
	*kClient
}

func (p *kLikeServiceClient) LikeAction(ctx context.Context, Req *likes.DouyinFavoriteActionRequest, callOptions ...callopt.Option) (r *likes.DouyinFavoriteActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LikeAction(ctx, Req)
}

func (p *kLikeServiceClient) LikeList(ctx context.Context, Req *likes.DouyinFavoriteListRequest, callOptions ...callopt.Option) (r *likes.DouyinFavoriteListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LikeList(ctx, Req)
}
